insert into licencia (lic_id, nombre, descripcion) values (1, 'Gratuito', 'Garden');
insert into licencia (lic_id, nombre, descripcion) values (2, 'Con Lincencia', 'Jewelry');
insert into licencia (lic_id, nombre, descripcion) values (3, 'Pago unico', 'Clothing');
insert into licencia (lic_id, nombre, descripcion) values (4, 'Subscripcion', 'Jewelry');
insert into licencia (lic_id, nombre, descripcion) values (5, 'Gratuito', 'Beauty');
insert into licencia (lic_id, nombre, descripcion) values (6, 'Con Lincencia', 'Jewelry');
insert into licencia (lic_id, nombre, descripcion) values (7, 'Pago unico', 'Outdoors');
insert into licencia (lic_id, nombre, descripcion) values (8, 'Subscripcion', 'Grocery');
insert into licencia (lic_id, nombre, descripcion) values (9, 'Gratuito', 'Tools');
insert into licencia (lic_id, nombre, descripcion) values (10, 'Con Lincencia', 'Books');
insert into licencia (lic_id, nombre, descripcion) values (11, 'Pago unico', 'Kids');
insert into licencia (lic_id, nombre, descripcion) values (12, 'Subscripcion', 'Games');
insert into licencia (lic_id, nombre, descripcion) values (13, 'Gratuito', 'Baby');
insert into licencia (lic_id, nombre, descripcion) values (14, 'Con Lincencia', 'Baby');
insert into licencia (lic_id, nombre, descripcion) values (15, 'Pago unico', 'Music');
insert into licencia (lic_id, nombre, descripcion) values (16, 'Subscripcion', 'Music');
insert into licencia (lic_id, nombre, descripcion) values (17, 'Gratuito', 'Outdoors');
insert into licencia (lic_id, nombre, descripcion) values (18, 'Con Lincencia', 'Tools');
insert into licencia (lic_id, nombre, descripcion) values (19, 'Pago unico', 'Automotive');
insert into licencia (lic_id, nombre, descripcion) values (20, 'Subscripcion', 'Grocery');
insert into licencia (lic_id, nombre, descripcion) values (21, 'Gratuito', 'Outdoors');
insert into licencia (lic_id, nombre, descripcion) values (22, 'Con Lincencia', 'Shoes');
insert into licencia (lic_id, nombre, descripcion) values (23, 'Pago unico', 'Automotive');
insert into licencia (lic_id, nombre, descripcion) values (24, 'Subscripcion', 'Games');
insert into licencia (lic_id, nombre, descripcion) values (25, 'Gratuito', 'Toys');
insert into licencia (lic_id, nombre, descripcion) values (26, 'Con Lincencia', 'Toys');
insert into licencia (lic_id, nombre, descripcion) values (27, 'Pago unico', 'Music');
insert into licencia (lic_id, nombre, descripcion) values (28, 'Subscripcion', 'Clothing');
insert into licencia (lic_id, nombre, descripcion) values (29, 'Gratuito', 'Books');
insert into licencia (lic_id, nombre, descripcion) values (30, 'Con Lincencia', 'Industrial');
insert into licencia (lic_id, nombre, descripcion) values (31, 'Pago unico', 'Automotive');
insert into licencia (lic_id, nombre, descripcion) values (32, 'Subscripcion', 'Music');
insert into licencia (lic_id, nombre, descripcion) values (33, 'Gratuito', 'Baby');
insert into licencia (lic_id, nombre, descripcion) values (34, 'Con Lincencia', 'Toys');
insert into licencia (lic_id, nombre, descripcion) values (35, 'Pago unico', 'Games');
insert into licencia (lic_id, nombre, descripcion) values (36, 'Subscripcion', 'Electronics');
insert into licencia (lic_id, nombre, descripcion) values (37, 'Gratuito', 'Home');
insert into licencia (lic_id, nombre, descripcion) values (38, 'Con Lincencia', 'Home');
insert into licencia (lic_id, nombre, descripcion) values (39, 'Pago unico', 'Books');
insert into licencia (lic_id, nombre, descripcion) values (40, 'Subscripcion', 'Automotive');
insert into licencia (lic_id, nombre, descripcion) values (41, 'Gratuito', 'Books');
insert into licencia (lic_id, nombre, descripcion) values (42, 'Con Lincencia', 'Jewelry');
insert into licencia (lic_id, nombre, descripcion) values (43, 'Pago unico', 'Movies');
insert into licencia (lic_id, nombre, descripcion) values (44, 'Subscripcion', 'Jewelry');
insert into licencia (lic_id, nombre, descripcion) values (45, 'Gratuito', 'Shoes');
insert into licencia (lic_id, nombre, descripcion) values (46, 'Con Lincencia', 'Outdoors');
insert into licencia (lic_id, nombre, descripcion) values (47, 'Pago unico', 'Books');
insert into licencia (lic_id, nombre, descripcion) values (48, 'Subscripcion', 'Games');
insert into licencia (lic_id, nombre, descripcion) values (49, 'Gratuito', 'Garden');
insert into licencia (lic_id, nombre, descripcion) values (50, 'Con Lincencia', 'Health');
insert into licencia (lic_id, nombre, descripcion) values (51, 'Pago unico', 'Toys');
insert into licencia (lic_id, nombre, descripcion) values (52, 'Subscripcion', 'Computers');
insert into licencia (lic_id, nombre, descripcion) values (53, 'Gratuito', 'Electronics');
insert into licencia (lic_id, nombre, descripcion) values (54, 'Con Lincencia', 'Grocery');
insert into licencia (lic_id, nombre, descripcion) values (55, 'Pago unico', 'Sports');
insert into licencia (lic_id, nombre, descripcion) values (56, 'Subscripcion', 'Electronics');
insert into licencia (lic_id, nombre, descripcion) values (57, 'Gratuito', 'Kids');
insert into licencia (lic_id, nombre, descripcion) values (58, 'Con Lincencia', 'Outdoors');
insert into licencia (lic_id, nombre, descripcion) values (59, 'Pago unico', 'Music');
insert into licencia (lic_id, nombre, descripcion) values (60, 'Subscripcion', 'Electronics');
insert into licencia (lic_id, nombre, descripcion) values (61, 'Gratuito', 'Outdoors');
insert into licencia (lic_id, nombre, descripcion) values (62, 'Con Lincencia', 'Electronics');
insert into licencia (lic_id, nombre, descripcion) values (63, 'Pago unico', 'Movies');
insert into licencia (lic_id, nombre, descripcion) values (64, 'Subscripcion', 'Industrial');
insert into licencia (lic_id, nombre, descripcion) values (65, 'Gratuito', 'Jewelry');
insert into licencia (lic_id, nombre, descripcion) values (66, 'Con Lincencia', 'Electronics');
insert into licencia (lic_id, nombre, descripcion) values (67, 'Pago unico', 'Outdoors');
insert into licencia (lic_id, nombre, descripcion) values (68, 'Subscripcion', 'Jewelry');
insert into licencia (lic_id, nombre, descripcion) values (69, 'Gratuito', 'Garden');
insert into licencia (lic_id, nombre, descripcion) values (70, 'Con Lincencia', 'Toys');
insert into licencia (lic_id, nombre, descripcion) values (71, 'Pago unico', 'Outdoors');
insert into licencia (lic_id, nombre, descripcion) values (72, 'Subscripcion', 'Sports');
insert into licencia (lic_id, nombre, descripcion) values (73, 'Gratuito', 'Movies');
insert into licencia (lic_id, nombre, descripcion) values (74, 'Con Lincencia', 'Toys');
insert into licencia (lic_id, nombre, descripcion) values (75, 'Pago unico', 'Sports');
insert into licencia (lic_id, nombre, descripcion) values (76, 'Subscripcion', 'Sports');
insert into licencia (lic_id, nombre, descripcion) values (77, 'Gratuito', 'Jewelry');
insert into licencia (lic_id, nombre, descripcion) values (78, 'Con Lincencia', 'Toys');
insert into licencia (lic_id, nombre, descripcion) values (79, 'Pago unico', 'Automotive');
insert into licencia (lic_id, nombre, descripcion) values (80, 'Subscripcion', 'Health');
insert into licencia (lic_id, nombre, descripcion) values (81, 'Gratuito', 'Health');
insert into licencia (lic_id, nombre, descripcion) values (82, 'Con Lincencia', 'Grocery');
insert into licencia (lic_id, nombre, descripcion) values (83, 'Pago unico', 'Garden');
insert into licencia (lic_id, nombre, descripcion) values (84, 'Subscripcion', 'Clothing');
insert into licencia (lic_id, nombre, descripcion) values (85, 'Gratuito', 'Jewelry');
insert into licencia (lic_id, nombre, descripcion) values (86, 'Con Lincencia', 'Garden');
insert into licencia (lic_id, nombre, descripcion) values (87, 'Pago unico', 'Industrial');
insert into licencia (lic_id, nombre, descripcion) values (88, 'Subscripcion', 'Kids');
insert into licencia (lic_id, nombre, descripcion) values (89, 'Gratuito', 'Jewelry');
insert into licencia (lic_id, nombre, descripcion) values (90, 'Con Lincencia', 'Toys');
insert into licencia (lic_id, nombre, descripcion) values (91, 'Pago unico', 'Health');
insert into licencia (lic_id, nombre, descripcion) values (92, 'Subscripcion', 'Automotive');
insert into licencia (lic_id, nombre, descripcion) values (93, 'Gratuito', 'Tools');
insert into licencia (lic_id, nombre, descripcion) values (94, 'Con Lincencia', 'Industrial');
insert into licencia (lic_id, nombre, descripcion) values (95, 'Pago unico', 'Jewelry');
insert into licencia (lic_id, nombre, descripcion) values (96, 'Subscripcion', 'Home');
insert into licencia (lic_id, nombre, descripcion) values (97, 'Gratuito', 'Grocery');
insert into licencia (lic_id, nombre, descripcion) values (98, 'Con Lincencia', 'Toys');
insert into licencia (lic_id, nombre, descripcion) values (99, 'Pago unico', 'Music');
insert into licencia (lic_id, nombre, descripcion) values (100, 'Subscripcion', 'Grocery');
insert into licencia (lic_id, nombre, descripcion) values (101, 'Gratuito', 'Music');
insert into licencia (lic_id, nombre, descripcion) values (102, 'Con Lincencia', 'Music');
insert into licencia (lic_id, nombre, descripcion) values (103, 'Pago unico', 'Kids');
insert into licencia (lic_id, nombre, descripcion) values (104, 'Subscripcion', 'Jewelry');
insert into licencia (lic_id, nombre, descripcion) values (105, 'Gratuito', 'Movies');
insert into licencia (lic_id, nombre, descripcion) values (106, 'Con Lincencia', 'Industrial');
insert into licencia (lic_id, nombre, descripcion) values (107, 'Pago unico', 'Clothing');
insert into licencia (lic_id, nombre, descripcion) values (108, 'Subscripcion', 'Electronics');
insert into licencia (lic_id, nombre, descripcion) values (109, 'Gratuito', 'Shoes');
insert into licencia (lic_id, nombre, descripcion) values (110, 'Con Lincencia', 'Electronics');
insert into licencia (lic_id, nombre, descripcion) values (111, 'Pago unico', 'Jewelry');
insert into licencia (lic_id, nombre, descripcion) values (112, 'Subscripcion', 'Electronics');
insert into licencia (lic_id, nombre, descripcion) values (113, 'Gratuito', 'Industrial');
insert into licencia (lic_id, nombre, descripcion) values (114, 'Con Lincencia', 'Home');
insert into licencia (lic_id, nombre, descripcion) values (115, 'Pago unico', 'Clothing');
insert into licencia (lic_id, nombre, descripcion) values (116, 'Subscripcion', 'Garden');
insert into licencia (lic_id, nombre, descripcion) values (117, 'Gratuito', 'Electronics');
insert into licencia (lic_id, nombre, descripcion) values (118, 'Con Lincencia', 'Outdoors');
insert into licencia (lic_id, nombre, descripcion) values (119, 'Pago unico', 'Books');
insert into licencia (lic_id, nombre, descripcion) values (120, 'Subscripcion', 'Clothing');
insert into licencia (lic_id, nombre, descripcion) values (121, 'Gratuito', 'Home');
insert into licencia (lic_id, nombre, descripcion) values (122, 'Con Lincencia', 'Books');
insert into licencia (lic_id, nombre, descripcion) values (123, 'Pago unico', 'Music');
insert into licencia (lic_id, nombre, descripcion) values (124, 'Subscripcion', 'Shoes');
insert into licencia (lic_id, nombre, descripcion) values (125, 'Gratuito', 'Music');
insert into licencia (lic_id, nombre, descripcion) values (126, 'Con Lincencia', 'Baby');
insert into licencia (lic_id, nombre, descripcion) values (127, 'Pago unico', 'Kids');
insert into licencia (lic_id, nombre, descripcion) values (128, 'Subscripcion', 'Health');
insert into licencia (lic_id, nombre, descripcion) values (129, 'Gratuito', 'Outdoors');
insert into licencia (lic_id, nombre, descripcion) values (130, 'Con Lincencia', 'Music');
insert into licencia (lic_id, nombre, descripcion) values (131, 'Pago unico', 'Games');
insert into licencia (lic_id, nombre, descripcion) values (132, 'Subscripcion', 'Computers');
insert into licencia (lic_id, nombre, descripcion) values (133, 'Gratuito', 'Health');
insert into licencia (lic_id, nombre, descripcion) values (134, 'Con Lincencia', 'Industrial');
insert into licencia (lic_id, nombre, descripcion) values (135, 'Pago unico', 'Outdoors');
insert into licencia (lic_id, nombre, descripcion) values (136, 'Subscripcion', 'Tools');
insert into licencia (lic_id, nombre, descripcion) values (137, 'Gratuito', 'Garden');
insert into licencia (lic_id, nombre, descripcion) values (138, 'Con Lincencia', 'Jewelry');
insert into licencia (lic_id, nombre, descripcion) values (139, 'Pago unico', 'Health');
insert into licencia (lic_id, nombre, descripcion) values (140, 'Subscripcion', 'Beauty');
insert into licencia (lic_id, nombre, descripcion) values (141, 'Gratuito', 'Baby');
insert into licencia (lic_id, nombre, descripcion) values (142, 'Con Lincencia', 'Electronics');
insert into licencia (lic_id, nombre, descripcion) values (143, 'Pago unico', 'Electronics');
insert into licencia (lic_id, nombre, descripcion) values (144, 'Subscripcion', 'Books');
insert into licencia (lic_id, nombre, descripcion) values (145, 'Gratuito', 'Tools');
insert into licencia (lic_id, nombre, descripcion) values (146, 'Con Lincencia', 'Games');
insert into licencia (lic_id, nombre, descripcion) values (147, 'Pago unico', 'Jewelry');
insert into licencia (lic_id, nombre, descripcion) values (148, 'Subscripcion', 'Baby');
insert into licencia (lic_id, nombre, descripcion) values (149, 'Gratuito', 'Computers');
insert into licencia (lic_id, nombre, descripcion) values (150, 'Con Lincencia', 'Music');
insert into licencia (lic_id, nombre, descripcion) values (151, 'Pago unico', 'Toys');
insert into licencia (lic_id, nombre, descripcion) values (152, 'Subscripcion', 'Sports');
insert into licencia (lic_id, nombre, descripcion) values (153, 'Gratuito', 'Outdoors');
insert into licencia (lic_id, nombre, descripcion) values (154, 'Con Lincencia', 'Outdoors');
insert into licencia (lic_id, nombre, descripcion) values (155, 'Pago unico', 'Health');
insert into licencia (lic_id, nombre, descripcion) values (156, 'Subscripcion', 'Electronics');
insert into licencia (lic_id, nombre, descripcion) values (157, 'Gratuito', 'Baby');
insert into licencia (lic_id, nombre, descripcion) values (158, 'Con Lincencia', 'Outdoors');
insert into licencia (lic_id, nombre, descripcion) values (159, 'Pago unico', 'Grocery');
insert into licencia (lic_id, nombre, descripcion) values (160, 'Subscripcion', 'Tools');
insert into licencia (lic_id, nombre, descripcion) values (161, 'Gratuito', 'Grocery');
insert into licencia (lic_id, nombre, descripcion) values (162, 'Con Lincencia', 'Jewelry');
insert into licencia (lic_id, nombre, descripcion) values (163, 'Pago unico', 'Beauty');
insert into licencia (lic_id, nombre, descripcion) values (164, 'Subscripcion', 'Toys');
insert into licencia (lic_id, nombre, descripcion) values (165, 'Gratuito', 'Automotive');
insert into licencia (lic_id, nombre, descripcion) values (166, 'Con Lincencia', 'Books');
insert into licencia (lic_id, nombre, descripcion) values (167, 'Pago unico', 'Clothing');
insert into licencia (lic_id, nombre, descripcion) values (168, 'Subscripcion', 'Grocery');
insert into licencia (lic_id, nombre, descripcion) values (169, 'Gratuito', 'Clothing');
insert into licencia (lic_id, nombre, descripcion) values (170, 'Con Lincencia', 'Automotive');
insert into licencia (lic_id, nombre, descripcion) values (171, 'Pago unico', 'Garden');
insert into licencia (lic_id, nombre, descripcion) values (172, 'Subscripcion', 'Kids');
insert into licencia (lic_id, nombre, descripcion) values (173, 'Gratuito', 'Sports');
insert into licencia (lic_id, nombre, descripcion) values (174, 'Con Lincencia', 'Grocery');
insert into licencia (lic_id, nombre, descripcion) values (175, 'Pago unico', 'Health');
insert into licencia (lic_id, nombre, descripcion) values (176, 'Subscripcion', 'Sports');
insert into licencia (lic_id, nombre, descripcion) values (177, 'Gratuito', 'Toys');
insert into licencia (lic_id, nombre, descripcion) values (178, 'Con Lincencia', 'Automotive');
insert into licencia (lic_id, nombre, descripcion) values (179, 'Pago unico', 'Kids');
insert into licencia (lic_id, nombre, descripcion) values (180, 'Subscripcion', 'Electronics');
insert into licencia (lic_id, nombre, descripcion) values (181, 'Gratuito', 'Music');
insert into licencia (lic_id, nombre, descripcion) values (182, 'Con Lincencia', 'Garden');
insert into licencia (lic_id, nombre, descripcion) values (183, 'Pago unico', 'Shoes');
insert into licencia (lic_id, nombre, descripcion) values (184, 'Subscripcion', 'Shoes');
insert into licencia (lic_id, nombre, descripcion) values (185, 'Gratuito', 'Beauty');
insert into licencia (lic_id, nombre, descripcion) values (186, 'Con Lincencia', 'Automotive');
insert into licencia (lic_id, nombre, descripcion) values (187, 'Pago unico', 'Baby');
insert into licencia (lic_id, nombre, descripcion) values (188, 'Subscripcion', 'Beauty');
insert into licencia (lic_id, nombre, descripcion) values (189, 'Gratuito', 'Beauty');
insert into licencia (lic_id, nombre, descripcion) values (190, 'Con Lincencia', 'Clothing');
insert into licencia (lic_id, nombre, descripcion) values (191, 'Pago unico', 'Shoes');
insert into licencia (lic_id, nombre, descripcion) values (192, 'Subscripcion', 'Industrial');
insert into licencia (lic_id, nombre, descripcion) values (193, 'Gratuito', 'Tools');
insert into licencia (lic_id, nombre, descripcion) values (194, 'Con Lincencia', 'Garden');
insert into licencia (lic_id, nombre, descripcion) values (195, 'Pago unico', 'Movies');
insert into licencia (lic_id, nombre, descripcion) values (196, 'Subscripcion', 'Home');
insert into licencia (lic_id, nombre, descripcion) values (197, 'Gratuito', 'Automotive');
insert into licencia (lic_id, nombre, descripcion) values (198, 'Con Lincencia', 'Outdoors');
insert into licencia (lic_id, nombre, descripcion) values (199, 'Pago unico', 'Tools');
insert into licencia (lic_id, nombre, descripcion) values (200, 'Subscripcion', 'Books');
