insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (1, 3, 'REMEDYREPACK INC.', 72);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (2, 2, 'DAVA Pharmaceuticals, Inc.', 19);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (3, 5, 'Mylan Institutional LLC', 163);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (4, 5, 'Proficient Rx LP', 45);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (5, 4, 'Melaleuca Inc.', 40);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (6, 3, 'Eisai Inc.', 140);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (7, 5, 'Walgreen Company', 163);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (8, 3, 'International Medication Systems, Limited', 32);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (9, 2, 'Teva Pharmaceuticals USA Inc', 186);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (10, 1, 'Bayer HealthCare Consumer Care', 99);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (11, 3, 'Teva Pharmaceuticals USA Inc', 83);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (12, 3, 'Jubilant HollisterStier LLC', 15);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (13, 3, 'NATURE REPUBLIC CO., LTD.', 47);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (14, 4, 'Fresenius Kabi USA, LLC', 61);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (15, 4, 'Integra Health International, S.A. de C.V.', 136);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (16, 5, 'Menper Distributors, Inc.', 23);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (17, 5, 'Nationwide Laboratories, LLC', 32);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (18, 1, 'BioActive Nutritional, Inc.', 92);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (19, 1, 'REMEDYREPACK INC.', 163);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (20, 1, 'Sandoz Inc', 158);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (21, 2, 'Dharma Research, Inc.', 144);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (22, 1, 'Island Abbey Foods Ltd.', 145);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (23, 2, 'OnPoint, Inc', 195);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (24, 4, 'Med Health Pharma, LLC', 36);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (25, 2, 'Nelco Laboratories, Inc.', 36);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (26, 2, 'Bryant Ranch Prepack', 40);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (27, 2, 'Eon Labs, Inc.', 27);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (28, 5, 'PALADIN LABORATORIES (USA) INC', 20);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (29, 3, 'Dolgencorp, LLC', 147);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (30, 5, 'Amphastar Pharmaceuticals, Inc.', 138);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (31, 1, 'Bonne Bell LLC', 93);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (32, 2, 'Care One (American Sales Company)', 193);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (33, 4, 'Cardinal Health', 196);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (34, 1, 'Sun Pharmaceutical Industries Limited', 4);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (35, 5, 'Oak Pharmaceuticals, Inc. (Subsidiary of Akorn, Inc.)', 52);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (36, 5, 'Apotex Corp.', 92);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (37, 1, 'DeMoulas Market Basket', 29);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (38, 2, 'Jubilant HollisterStier LLC', 91);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (39, 2, 'REMEDYREPACK INC.', 57);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (40, 2, 'Actavis Pharma, Inc.', 98);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (41, 5, 'Richmond Pharmaceuticals Inc.', 91);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (42, 2, 'Nelco Laboratories, Inc.', 166);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (43, 5, 'JAFRA COSMETICS INTERNATIONAL', 126);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (44, 1, 'Western Family Foods, Inc.', 78);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (45, 5, 'WALGREEN COMPANY', 85);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (46, 4, 'Guthy-Renker LLC', 46);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (47, 4, 'Rugby Laboratories', 89);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (48, 2, 'A-S Medication Solutions LLC', 51);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (49, 4, 'Ventura Corporation LTD.', 170);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (50, 1, 'Avon Products, Inc.', 37);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (51, 1, 'Winthrop U.S.', 58);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (52, 5, 'REMEDYREPACK INC.', 172);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (53, 1, 'Major Pharmaceuticals', 176);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (54, 2, 'Pfizer Laboratories Div Pfizer Inc', 26);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (55, 1, 'GOWOONSESANG COSMETICS CO., LTD.', 136);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (56, 5, 'PD-Rx Pharmaceuticals, Inc.', 60);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (57, 5, 'Western Family Foods Inc', 170);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (58, 5, 'Newton Laboratories, Inc.', 162);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (59, 2, 'Medi-Physics Inc.', 190);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (60, 4, 'Janssen Pharmaceuticals, Inc.', 35);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (61, 4, 'North Safety Products', 171);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (62, 5, 'McKesson', 18);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (63, 2, 'Lil'' Drug Store Products, Inc.', 121);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (64, 4, 'Dispensing Solutions, Inc.', 31);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (65, 1, 'Genesis', 103);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (66, 1, 'McKesson Packaging Services Business Unit of McKesson Corporation', 177);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (67, 4, 'NCS HealthCare of KY, Inc dba Vangard Labs', 155);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (68, 2, 'Dharma Research, inc.', 41);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (69, 5, 'Medline Industries, Inc.', 196);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (70, 4, 'Eau Zone Oils & Fragrances LTD', 78);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (71, 4, 'Tamnamo Co., Ltd', 115);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (72, 4, 'Aphena Pharma Solutions - Tennessee, LLC', 72);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (73, 3, 'Physicians Formula Inc', 172);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (74, 3, 'Conney Safety Products, LLC', 98);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (75, 5, 'Aptalis Pharma US, Inc.', 42);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (76, 1, 'Mission Hills S.A de C.V', 171);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (77, 1, 'Actavis Pharma, Inc.', 16);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (78, 4, 'Ionx Holdings d/b/a HelloLife LLC', 14);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (79, 3, 'Allermed Laboratories, Inc.', 148);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (80, 1, 'Nash-Finch Company', 123);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (81, 4, 'Aidarex Pharmaceuticals LLC', 40);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (82, 2, 'SHISEIDO AMERICA INC.', 21);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (83, 3, 'Global Pharmaceuticals, Division of Impax Laboratories Inc.', 90);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (84, 3, 'Blenheim Pharmacal, Inc.', 179);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (85, 4, 'SHISEIDO CO., LTD.', 9);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (86, 3, 'State of Florida DOH Central Pharmacy', 24);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (87, 5, 'Pfizer Laboratories Div Pfizer Inc', 148);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (88, 3, 'Supervalu Inc', 36);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (89, 5, 'Guerbet LLC', 133);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (90, 5, 'Allergy Laboratories, Inc.', 127);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (91, 1, 'KAISER FOUNDATION HOSPITALS', 15);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (92, 5, 'Ohm Laboratories Inc.', 105);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (93, 1, 'Natural Health Supply', 133);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (94, 2, 'Septodont Inc.', 149);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (95, 5, 'Boehringer Ingelheim Pharmaceuticals Inc.', 178);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (96, 3, 'Aditya Labs Inc', 26);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (97, 5, 'Natural Creations, Inc.', 30);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (98, 2, 'Herbion Pakistan (Pvt.) Ltd.', 92);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (99, 3, 'PharmWest Inc.', 57);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (100, 2, 'Clinical Solutions Wholesale', 167);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (101, 5, 'CVS Pharmacy', 162);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (102, 4, 'General Injectables & Vaccines, Inc', 144);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (103, 3, 'Nelco Laboratories, Inc.', 40);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (104, 1, 'American Sales Company', 168);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (105, 4, 'Perrigo New York Inc', 13);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (106, 3, 'BluePoint Laboratories', 72);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (107, 2, 'Sanum Kehlbeck GmbH & Co. KG', 6);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (108, 1, 'Woonsocket Prescription Center (CVS)', 71);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (109, 1, 'Valu Merchandisers, Co.', 94);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (110, 2, 'Hanover Pen Corp dba HPC Global', 135);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (111, 4, 'Nature''s Way Holding Co.', 135);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (112, 1, 'Watson Pharma, Inc.', 15);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (113, 2, 'Antigen Laboratories, Inc.', 39);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (114, 4, 'Target Corporation', 180);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (115, 4, 'Energetix Corp', 164);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (116, 1, 'Feelgood Health', 86);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (117, 3, 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', 130);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (118, 5, 'Merck Sharp & Dohme Corp.', 171);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (119, 1, 'Ascend Laboratories, LLC', 69);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (120, 5, 'REMEDYREPACK INC.', 163);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (121, 5, 'Nelco Laboratories, Inc.', 55);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (122, 5, 'REMEDYREPACK INC.', 142);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (123, 1, 'Bare Escentuals Beauty Inc.', 122);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (124, 4, 'Sun Pharmaceutical Industries Limited', 33);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (125, 2, 'REMEDYREPACK INC.', 74);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (126, 4, 'BluePoint Laboratories', 184);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (127, 1, 'Lake Erie Medical DBA Quality Care Products LLC', 68);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (128, 1, 'Antigen Laboratories, Inc.', 111);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (129, 4, 'Pfizer Laboratories Div Pfizer Inc', 116);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (130, 4, 'Heritage Pharmaceuticals Inc.', 5);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (131, 3, 'State of Florida DOH Central Pharmacy', 101);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (132, 3, 'Shopko Stores Operating Co., LLC', 189);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (133, 4, 'Richmond Pharmaceuticals Inc.', 159);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (134, 2, 'WOONSOCKET PRESCRIPTION CENTER,INCORPORATED', 172);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (135, 3, 'Spear Dermatology Products Inc', 199);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (136, 1, 'Natures Way Holding Co.', 120);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (137, 3, 'Teva Parenteral Medicines, Inc.', 38);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (138, 5, 'Teva Pharmaceuticals USA Inc', 139);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (139, 5, 'Bryomed Inc.', 152);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (140, 3, 'Rimmel Inc.', 4);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (141, 4, 'Nelco Laboratories, Inc.', 91);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (142, 5, 'REMEDYREPACK INC.', 167);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (143, 4, 'Genuine Virgin Aloe Corporation', 185);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (144, 3, 'Med-Health Pharma, LLC', 44);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (145, 2, 'NextSource Biotechnology, LLC', 83);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (146, 3, 'Eduard Gerlach GmbH', 124);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (147, 1, 'TJA Health LLC', 185);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (148, 3, 'Apotheca Company', 111);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (149, 5, 'Lupin Pharmaceuticals, Inc.', 191);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (150, 1, 'L''Oreal USA Products Inc', 74);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (151, 2, 'LUEN FOOK MEDICINE SDN. BHD.', 72);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (152, 5, 'Ventura Corporation LTD', 16);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (153, 1, 'International Cosmetics Ltd.', 119);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (154, 1, 'Energique, Inc.', 30);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (155, 2, 'Antigen Laboratories, Inc.', 83);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (156, 5, 'L''Oreal USA Products Inc', 194);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (157, 1, 'MARKSANS PHARMA LIMITED', 89);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (158, 1, 'Emilia Personal Care Inc.', 86);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (159, 5, 'La Prairie, Inc.', 181);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (160, 5, 'Arbonne International, LLC', 185);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (161, 2, 'A-S Medication Solutions LLC', 169);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (162, 5, 'Wal-Mart Stores Inc', 139);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (163, 2, 'OMP, INC.', 64);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (164, 1, 'Physicians Total Care, Inc.', 188);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (165, 4, 'Antigen Laboratories, Inc.', 25);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (166, 2, 'ReadyMeds', 24);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (167, 1, 'Clinical Solutions Wholesale', 173);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (168, 1, 'Massco Dental A Division of Dunagin Pharmaceuticals', 135);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (169, 3, 'Target Corporation', 60);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (170, 3, 'E. FOUGERA & CO. A division of Fougera Pharmaceuticals Inc.', 99);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (171, 1, 'Cardinal Health', 21);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (172, 2, 'Janssen Products LP', 176);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (173, 5, 'Keltman Pharmaceuticals Inc.', 110);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (174, 4, 'Physicians Total Care, Inc.', 66);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (175, 2, 'SJ Creations, Inc.', 22);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (176, 3, 'Physicians Total Care, Inc.', 19);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (177, 4, 'Preferred Pharmaceuticals, Inc.', 16);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (178, 2, 'Mylan Pharmaceuticals Inc.', 103);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (179, 4, 'DZA Brands LLC', 124);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (180, 5, 'Dolgencorp, Inc. (DOLLAR GENERAL & REXALL)', 187);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (181, 5, 'Hawthorne Pharmaceuticals, Inc.', 60);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (182, 2, 'Ranbaxy Pharmaceuticals Inc.', 71);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (183, 2, 'Zydus Pharmaceuticals (USA) Inc.', 183);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (184, 4, 'GLENVIEW PHARMA INC.', 198);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (185, 2, 'Ventura Corporation (San Juan, P.R)', 94);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (186, 5, 'Stephen L. LaFrance Pharmacy, Inc.', 58);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (187, 5, 'AGABANG & COMPANY', 7);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (188, 1, 'CVS Pharmacy', 118);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (189, 1, 'Colgate-Palmolive Company', 112);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (190, 4, 'Dr. Reddy''s Laboratories Ltd', 101);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (191, 1, 'THEFACESHOP CO., LTD.', 32);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (192, 2, 'Jubilant HollisterStier LLC', 78);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (193, 1, 'Allergy Laboratories, Inc.', 150);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (194, 2, 'Cardinal Health', 164);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (195, 5, 'Kingdom Animalia, LLC. DBA Hourglass Cosmetics', 14);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (196, 2, 'Physicians Total Care, Inc.', 47);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (197, 3, 'Vertical Pharmaceuticals, Inc.', 187);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (198, 2, 'SAMSUNG PHARM IND. CO., LTD.', 44);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (199, 5, 'NCS HealthCare of KY, Inc dba Vangard Labs', 129);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (200, 5, 'Nostrum Laboratories Inc.', 92);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (201, 1, 'Nelco Laboratories, Inc.', 69);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (202, 5, 'Golden State Medical Supply, Inc.', 19);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (203, 4, 'Antigen Laboratories, Inc.', 170);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (204, 3, 'Natural Creations, Inc.', 95);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (205, 3, 'Physicians Total Care, Inc.', 32);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (206, 5, 'Lupin Pharmaceuticals, Inc.', 94);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (207, 4, 'Bare Escentuals Beauty Inc.', 4);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (208, 3, 'Meijer Distribution Inc', 115);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (209, 3, 'Aurobindo Pharma Limited', 146);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (210, 5, 'Johnson & Johnson Consumer Products Company, Division of Johnson & Johnson Consumer Companies, Inc.', 107);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (211, 4, 'Bausch & Lomb Incorporated', 32);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (212, 3, 'STAT Rx USA LLC', 141);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (213, 3, 'OUR FAMILY (Nash Finch Company)', 94);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (214, 1, 'Physicians Total Care, Inc.', 178);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (215, 1, 'Unit Dose Services', 186);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (216, 2, 'Mallinckrodt, Inc.', 193);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (217, 1, 'Preferred Pharmaceuticals, Inc', 178);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (218, 2, 'Perrigo New York Inc', 81);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (219, 1, 'Gil Pharmaceutical Corp', 80);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (220, 3, 'PUR MINERALS', 31);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (221, 2, 'KAISER FOUNDATION HOSPITALS', 80);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (222, 5, 'Wayne Concept Manufacturing Co Inc', 161);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (223, 1, 'Cardinal Health', 65);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (224, 2, 'Laboratoires Clarins S.A.', 54);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (225, 4, 'Baxter Healthcare Corporation', 65);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (226, 3, 'Blenheim Pharmacal, Inc.', 179);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (227, 3, 'PD-Rx Pharmaceuticals, Inc.', 105);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (228, 3, 'Apollo Health and Beauty Care', 129);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (229, 5, 'Kolmar Korea Co Ltd', 101);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (230, 2, 'Strategic Pharmaceutical Solutions, Inc. DBA VetSource', 135);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (231, 3, 'McKesson Contract Packaging', 191);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (232, 3, 'Cardinal Health', 8);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (233, 4, 'Rebel Distributors Corp', 175);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (234, 4, 'Uriel Pharmacy Inc.', 13);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (235, 4, 'Upsher-Smith Laboratories, Inc.', 41);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (236, 4, 'Triumph Pharmaceuticals Inc.', 63);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (237, 4, 'Neutrogena Corporation', 69);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (238, 1, 'STAT Rx USA LLC', 135);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (239, 5, 'State of Florida DOH Central Pharmacy', 3);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (240, 5, 'Dermarite Industries LLC', 36);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (241, 4, 'Nelco Laboratories, Inc.', 199);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (242, 4, 'Prasco Laboratories', 18);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (243, 1, 'INNOVATION SPECIALTIES', 12);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (244, 1, 'Sandoz Inc', 145);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (245, 3, 'W. H. Goodale Co. Inc.', 54);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (246, 3, 'Newton Laboratories, Inc.', 24);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (247, 1, 'Cardinal Health', 134);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (248, 2, 'HOMEOLAB USA INC.', 19);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (249, 5, 'Dr. Fresh LLC', 133);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (250, 1, 'CleanWell', 82);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (251, 3, 'BF ASCHER AND CO INC', 60);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (252, 1, 'ALK-Abello, Inc.', 31);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (253, 3, 'REMEDYREPACK INC.', 127);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (254, 4, 'Bath & Body Works, Inc.', 199);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (255, 3, 'Nelco Laboratories, Inc.', 106);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (256, 4, 'H E B', 140);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (257, 4, 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', 130);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (258, 3, 'ALK-Abello, Inc.', 163);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (259, 4, 'Sun Pharma Global FZE', 88);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (260, 3, 'Ohm Laboratories Inc.', 192);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (261, 4, 'PD-Rx Pharmaceuticals, Inc.', 82);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (262, 5, 'MedVantx, Inc.', 121);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (263, 5, 'Geiss, Destin & Dunn, Inc.', 182);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (264, 5, 'Apotheca Company', 149);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (265, 3, 'Major Pharmaceuticals', 145);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (266, 1, 'Bryant Ranch Prepack', 47);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (267, 1, 'American Health Packaging', 93);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (268, 1, 'Physicians Total Care, Inc.', 118);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (269, 1, 'Chattem, Inc.', 127);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (270, 2, 'Neutrogena Corporation', 88);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (271, 4, 'Apotex Corp.', 26);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (272, 3, 'F&CO Co., Ltd.', 180);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (273, 1, 'Sage Products, Inc.', 175);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (274, 1, 'Aidarex Pharmaceuticals LLC', 154);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (275, 1, 'Aphena Pharma Solutions - Tennessee, LLC', 183);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (276, 3, 'Methapharm Inc.', 64);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (277, 1, 'Select Brand', 124);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (278, 5, 'Aidarex Pharmaceuticals LLC', 52);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (279, 5, 'Breckenridge Pharmaceutical, Inc.', 135);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (280, 1, 'American Sales Company', 64);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (281, 3, 'Mutual Pharmaceutical Company, Inc.', 113);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (282, 3, 'Physicians Total Care, Inc.', 39);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (283, 3, 'Sandoz Inc', 148);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (284, 5, 'Vi-Jon', 180);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (285, 4, 'Zydus Pharmaceuticals (USA) Inc.', 17);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (286, 5, 'Natural Health Supply', 96);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (287, 5, 'Sandoz Inc', 38);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (288, 2, 'Schryver Medical Sales and Marketing, Inc.', 87);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (289, 1, 'The Dial Corporation', 69);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (290, 4, 'AR Medicom Inc.', 74);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (291, 2, 'Aqua Pharmaceuticals, LLC', 195);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (292, 4, 'RZN Nutraceuticals, Inc.', 191);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (293, 5, 'Allure Labs, Inc.', 64);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (294, 4, 'LG Household and Healthcare, Inc.', 16);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (295, 1, 'H2O Plus', 170);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (296, 3, 'Major Pharmaceuticals', 40);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (297, 1, 'H.J. Harkins Company, Inc.', 30);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (298, 4, 'Snuva, Inc.', 147);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (299, 2, 'American Sales Company', 48);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (300, 2, 'Good Neighbor Pharmacy', 3);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (301, 5, 'Dispensing Solutions, Inc.', 19);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (302, 3, 'H.J. Harkins Company, Inc.', 48);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (303, 3, 'Airgas-West, Inc.', 61);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (304, 4, 'Washington Homeopathic Products', 147);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (305, 1, 'Lupin Pharmaceuticals, Inc.', 59);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (306, 1, 'IGI Labs, Inc.', 29);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (307, 5, 'BioActive Nutritional, Inc.', 52);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (308, 4, 'Jubilant HollisterStier LLC', 68);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (309, 1, 'Rite Aid Corporation', 146);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (310, 1, 'Wyeth Pharmaceuticals Inc., a subsidiary of Pfizer Inc.', 44);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (311, 2, 'State of Florida DOH Central Pharmacy', 23);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (312, 1, 'Physicians Total Care, Inc.', 28);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (313, 1, 'Silarx Pharmaceuticals, Inc', 114);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (314, 3, 'ALK-Abello, Inc.', 44);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (315, 4, 'Nelco Laboratories, Inc.', 184);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (316, 1, 'Hi-Tech Pharmacal Co., Inc.', 79);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (317, 3, 'ASSURED (Greenbrier International, Inc.)', 76);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (318, 2, 'Carilion Materials Management', 141);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (319, 3, 'Mckesson Contract Packaging', 114);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (320, 2, 'BCM Cosmetique SAS', 117);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (321, 5, 'Natural Health Supply', 91);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (322, 1, 'Cardinal Health', 198);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (323, 5, 'Physicians Formula Inc', 1);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (324, 5, 'Sanum Kehlbeck GmbH & Co. KG', 106);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (325, 1, 'Antigen Laboratories, Inc.', 80);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (326, 4, 'Dr.Reddy''s Laboratories Limited', 65);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (327, 4, 'Genesis Pharmaceutical, Inc.', 25);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (328, 4, 'Physicians Total Care, Inc.', 137);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (329, 4, 'King Bio Inc.', 32);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (330, 3, 'AvPAK', 185);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (331, 3, 'McKesson Contract Packaging', 72);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (332, 2, 'Linde Gas North America LLC', 146);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (333, 4, 'Health Care Products', 18);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (334, 2, 'Ventura Corporation LTD', 150);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (335, 2, 'Meijer Distribution Inc', 128);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (336, 5, 'Physicians Total Care, Inc.', 69);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (337, 3, 'HOMEOLAB USA INC.', 123);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (338, 2, 'Respa Pharmaceuticals, Inc.', 9);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (339, 5, 'Citron Pharma LLC', 112);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (340, 3, 'ALK-Abello, Inc.', 7);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (341, 1, 'Amerisource Bergen', 107);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (342, 5, 'Wockhardt USA LLC.', 194);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (343, 2, 'Concept Laboratories, Inc.', 15);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (344, 1, 'Roberts Oxygen Company, Inc.', 27);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (345, 4, 'Cardinal Health', 85);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (346, 3, 'Clinical Solutions Wholesale', 194);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (347, 2, 'American Health Packaging', 126);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (348, 2, 'King Bio Inc.', 115);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (349, 1, 'Geiss, Destin + Dunmn, Inc', 158);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (350, 3, 'Melaleuca, Inc.', 144);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (351, 3, 'NCS HealthCare of KY, Inc dba Vangard Labs', 170);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (352, 5, 'AmerisourceBergen Drug Corporation (Good Neighbor Pharmacy) 24385', 170);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (353, 5, 'Nelco Laboratories, Inc.', 47);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (354, 5, 'REMEDYREPACK INC.', 71);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (355, 1, 'Hospira, Inc.', 39);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (356, 4, 'Nelco Laboratories, Inc.', 65);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (357, 4, 'Eon Labs, Inc.', 69);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (358, 2, 'Elizabeth Arden, Inc', 68);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (359, 3, 'Teva Pharmaceuticals USA Inc', 56);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (360, 5, 'Tom''s of Maine, Inc.', 112);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (361, 2, 'Physicians Total Care, Inc.', 29);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (362, 3, 'PD-Rx Pharmaceuticals, Inc.', 26);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (363, 1, 'Amedra Pharmaceuticals LLC', 74);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (364, 2, 'REMEDYREPACK INC.', 139);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (365, 2, 'Claris Lifesciences Inc.', 114);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (366, 1, 'Family Dollar (FAMILY WELLNESS)', 153);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (367, 3, 'Neutrogena Corporation', 98);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (368, 3, 'Rebel Distributors Corp', 173);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (369, 2, 'Chattem, Inc.', 6);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (370, 2, 'RedPharm Drug Inc.', 161);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (371, 3, 'Ventura Corporation LTD', 4);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (372, 5, 'State of Florida DOH Central Pharmacy', 99);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (373, 5, 'Profoot, Inc.', 144);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (374, 4, 'Publix Super Markets Inc', 115);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (375, 5, 'Noxell', 34);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (376, 5, 'Peace Medical Inc.', 88);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (377, 4, 'Preferred Pharmaceuticals, Inc', 55);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (378, 2, 'Amneal Pharmaceuticals of New York, LLC', 36);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (379, 4, 'Apotex Corp', 99);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (380, 2, 'Western Family Foods Inc', 3);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (381, 5, 'Avon Products, Inc', 123);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (382, 4, 'Teva Parenteral Medicines, Inc.', 177);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (383, 4, 'Nelco Laboratories, Inc.', 90);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (384, 1, 'Aurobindo Pharma Limited', 123);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (385, 4, 'Sandoz Inc.', 158);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (386, 4, 'Cardinal Health', 163);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (387, 3, 'Major Pharmaceuticals', 104);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (388, 4, 'BioActive Nutritional', 154);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (389, 4, 'Target Corporation', 132);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (390, 5, 'International Cosmetics Ltd.', 191);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (391, 4, 'West-ward Pharmaceutical Corp.', 145);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (392, 3, 'Natural Health Supply', 88);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (393, 2, 'ABCO Laboratories, Inc.', 54);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (394, 4, 'ProPhase Labs, Inc.', 93);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (395, 2, 'Rimmel Inc.', 116);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (396, 3, 'Aurobindo Pharma Limited', 199);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (397, 2, 'Rite Aid Corporation', 92);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (398, 3, 'The Mentholatum Company', 85);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (399, 2, 'Poly Pharmaceuticals, Inc.', 35);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (400, 1, 'Genentech, Inc.', 91);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (401, 2, 'Amerisource Bergen', 118);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (402, 4, 'Hospira, Inc.', 62);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (403, 2, 'CHANEL PARFUMS BEAUTE', 197);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (404, 1, 'Access Business Group LLC', 110);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (405, 4, 'American Health Packaging', 194);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (406, 1, 'Laboratoires Clarins S.A.', 36);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (407, 3, 'FRED''S, INC.', 147);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (408, 2, 'Uriel Pharmacy Inc.', 176);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (409, 4, 'Hope Pharmaceuticals', 118);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (410, 1, 'REMEDYREPACK INC.', 43);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (411, 2, 'Heel Inc', 193);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (412, 1, 'Shanghai Weierya Daily Chemicals Factory', 152);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (413, 3, 'State of Florida DOH Central Pharmacy', 108);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (414, 1, 'Nelco Laboratories, Inc.', 163);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (415, 3, 'X-GEN Pharmaceuticals, Inc.', 134);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (416, 1, 'Apotex Corp', 89);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (417, 2, 'Antigen Laboratories, Inc.', 165);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (418, 2, 'Advanced Apothecaries Inc. dba Health Depot', 95);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (419, 2, 'Premier Value', 135);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (420, 3, 'Merck Sharp & Dohme Corp.', 161);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (421, 5, 'Hevert Pharmaceuticals LLC', 157);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (422, 5, 'Triad Group', 135);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (423, 3, 'Northwind Pharmaceuticals', 75);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (424, 5, 'Asclemed USA, Inc.', 175);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (425, 4, 'Jafra Cosmetics International', 2);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (426, 1, 'Target Corporation', 22);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (427, 5, 'Physicians Total Care, Inc.', 139);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (428, 3, 'E. Fougera & Co. a division of Fougera Pharmaceuticals Inc.', 76);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (429, 2, 'MATERNAL SCIENCE, LLC', 97);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (430, 2, 'Proficient Rx LP', 143);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (431, 3, 'Premier Value (Chain Drug Consortium, LLC)', 195);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (432, 2, 'Antigen Laboratories, Inc.', 125);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (433, 3, 'King Bio Inc.', 172);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (434, 1, 'Natural Health Supply', 13);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (435, 2, 'Sam''s West Inc', 88);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (436, 5, 'L''Oreal USA Products Inc', 36);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (437, 4, 'Noven Therapeutics, LLC', 107);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (438, 4, 'Nelco Laboratories, Inc.', 33);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (439, 3, 'Lake Erie Medical DBA Quality Care Products LLC', 161);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (440, 4, 'American Sales Company', 126);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (441, 2, 'Lornamead', 140);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (442, 3, 'Bare Escentuals Beauty Inc.', 154);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (443, 1, 'Novartis Consumer Health Inc.', 110);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (444, 1, 'CCA Industries, Inc.', 12);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (445, 3, 'Tri-Coastal Design Company Inc.', 186);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (446, 2, 'REMEDYREPACK INC.', 160);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (447, 3, 'Blue Cross Laboratories, Inc.', 38);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (448, 5, 'Jubilant HollisterStier LLC', 73);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (449, 5, 'Merck Sharp & Dohme Corp.', 62);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (450, 2, 'Santarus, Inc.', 123);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (451, 2, 'STAT Rx USA LLC', 6);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (452, 4, 'Pliva, Inc', 147);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (453, 4, 'H.J. Harkins Company, Inc.', 196);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (454, 5, 'International Beauty Exchange', 86);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (455, 4, 'NATURE REPUBLIC CO., LTD.', 62);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (456, 5, 'Perrigo New York Inc', 11);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (457, 5, 'Pfizer Laboratories Div Pfizer Inc', 67);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (458, 4, 'McKesson Contract Packaging', 106);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (459, 4, 'REMEDYREPACK INC.', 88);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (460, 2, 'Kramer Novis', 84);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (461, 5, 'Access Business Group LLC', 169);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (462, 2, 'Preferred Pharmaceuticals, Inc.', 184);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (463, 3, 'Acme United Corporation', 158);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (464, 5, 'Eli Lilly and Company', 193);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (465, 5, 'Lake Erie Medical & Surgical Supply DBA Qualtiy Care Products LLC', 138);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (466, 5, 'Washington Homeopathic Products', 37);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (467, 1, 'Contract Pharmacy Services-PA', 118);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (468, 1, 'General Injectables & Vaccines, Inc', 186);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (469, 4, 'General Injectables and Vaccines, Inc.', 56);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (470, 5, 'McKesson', 79);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (471, 1, 'CHANEL PARUMS BEAUTE', 76);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (472, 2, 'ALK-Abello, Inc.', 92);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (473, 5, 'Kutol Products Company, Inc.', 142);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (474, 2, 'Arbor Pharmaceuticals, Inc.', 46);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (475, 1, 'ALK-Abello, Inc.', 116);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (476, 3, 'Teva Pharmaceuticals USA Inc', 145);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (477, 2, 'REMEDYREPACK INC.', 150);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (478, 4, 'SKINFOOD CO., LTD.', 198);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (479, 4, 'AbbVie Inc.', 63);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (480, 4, 'Apotex Corp.', 154);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (481, 5, 'Aphena Pharma Solutions - Tennessee, Inc.', 109);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (482, 4, 'ZO Skin Health, Inc.', 110);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (483, 5, 'Major Pharmaceuticals', 175);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (484, 1, 'BioActive Nutritional, Inc.', 94);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (485, 4, 'Revive Bioscience, Inc.', 97);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (486, 2, 'AvPAK', 11);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (487, 5, 'Antigen Laboratories, Inc.', 147);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (488, 2, 'Qualitest Pharmaceuticals', 91);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (489, 3, 'Physicians Total Care, Inc.', 185);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (490, 1, 'Shionogi Inc.', 45);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (491, 1, 'St Marys Medical Park Pharmacy', 133);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (492, 1, 'Bath & Body Works, Inc.', 160);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (493, 4, 'The Mentholatum Company', 160);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (494, 3, 'West-ward Pharmaceutical Corp.', 83);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (495, 2, 'Kroger Company', 64);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (496, 2, 'Boy Butter Lubes', 46);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (497, 3, 'Fusion Pharmaceuticals LLC', 148);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (498, 3, 'SCOT-TUSSIN Pharmacal Co., Inc.', 167);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (499, 1, 'Coty US LLC', 66);
insert into puntuacion (pun_id, puntuacion, comentario, fk_sof_id) values (500, 3, 'Harrison Specialty Co., Inc.', 99);
