<?php

namespace app\controllers\vistas;

use yii\db\ActiveRecord;

class vw_detalle_software extends ActiveRecord
{
    public static function tableName()
    {
        return parent::tableName(); // TODO: Change the autogenerated stub
    }
}