<?php

namespace app\models;

use yii\db\ActiveRecord;

class Desarrollador extends ActiveRecord
{
    public static function tableName()
    {
        return 'desarrollador'; // TODO: Change the autogenerated stub
    }
}